# Generated by Django 6.0.3 on 2026-03-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
    ]
